# Generated by Django 5.0.6 on 2024-05-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_paper', '0001_initial'),
        ('app_publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper_title_uz', models.CharField(max_length=255)),
                ('paper_title_en', models.CharField(max_length=255)),
                ('paper_annotation_uz', models.TextField()),
                ('paper_annotation_en', models.TextField()),
                ('count_views', models.IntegerField(default=0)),
                ('paper_references', models.URLField()),
                ('keywords', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper_sphere', models.ManyToManyField(to='app_paper.sphere')),
                ('publication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_publications.publications')),
            ],
            options={
                'db_table': 'abstract_model',
                'abstract': False,
            },
        ),
    ]
