# Generated by Django 5.0.6 on 2024-05-21 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_paper', '0002_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('position_uz', models.CharField(max_length=150)),
                ('position_en', models.CharField(max_length=150)),
                ('sphere_id', models.ManyToManyField(to='app_paper.sphere')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback/')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paper.papers')),
                ('Reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_paper.reviewers')),
            ],
        ),
    ]
