# Generated by Django 5.0.6 on 2024-05-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications_name_uz', models.CharField(max_length=255)),
                ('publications_name_en', models.CharField(max_length=255)),
                ('pub_image', models.ImageField(upload_to='publications/')),
                ('pub_file_uz', models.FileField(upload_to='publications/file-uz')),
                ('pub_file_en', models.FileField(upload_to='publications/file-en')),
                ('include_sphere', models.ManyToManyField(to='app_paper.sphere')),
            ],
        ),
    ]
