# Generated by Django 5.0.4 on 2024-05-19 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(max_length=255)),
                ('question_eng', models.CharField(max_length=255)),
                ('answer_uz', models.CharField(max_length=255)),
                ('answer_eng', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'faq',
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.CharField(max_length=125)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
            },
        ),
    ]
